services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=messages
      - POSTGRES_USER=filenest
      - POSTGRES_PASSWORD=filenest
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  rabbitmq:
    image: rabbitmq:3.11.0-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=filenest
      - RABBITMQ_DEFAULT_PASS=filenest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
  rabbitmq_data: