server:
  port: 8084

logging:
  level:
    root: info
    ru.zolotyh: debug

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: dzolotyh
    password: filenest

bot:
  name: file_nest_bot
  token: 999